[book]
authors = ["Tony Wu"]
language = "en"
multilingual = false
src = "src"
title = "ferrosaur"

[build]
build-dir = "dist"
create-missing = false
extra-watch-dirs = ["app", "../examples", "../crates"]

[rust]
edition = "2021"

[output.html]
additional-css = ["app/dist.css"]
additional-js = ["app/dist.js"]
default-theme = "ayu"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/tonywu6/ferrosaur"
hash-files = true
preferred-dark-theme = "ayu"
site-url = "/"

[output.html.playground]
runnable = false

[preprocessor.rustdoc-link]
after = ["links"]
cache-dir = "build"
command = "cargo bin mdbook-rustdoc-link"
manifest-dir = "."

[preprocessor.link-forever]
after = ["rustdoc-link"]
always-link = [".rs"]
book-url = "https://tonywu6.github.io/ferrosaur/"
command = "cargo bin mdbook-link-forever"

[preprocessor.alerts]
after = ["rustdoc-link"]
command = "cargo bin mdbook-alerts"

[preprocessor.app]
after = ["links"]
before = ["rustdoc-link"]
command = "deno run --allow-all app/build/mdbook.ts"

[_metadata.socials."/"]
image = "https://opengraph.githubassets.com/main/tonywu6/ferrosaur"
title = "ferrosaur"

[_metadata.socials."/examples/"]
title = "Examples"

[_metadata.socials."/reference/"]
title = "Reference"
